input {
  beats {
    port => 5044
  }
}

filter {
  # Ici tu peux ajouter des filtres selon ton format de logs
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{log_type}-%{+YYYY.MM.dd}"
  }
}
